services:
  database:
    container_name: educambi_db_mysql
    image: mysql:9.1
    build: mysql:9.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL__ROOT__PASSWORD}
      MYSQL_USER: ${MYSQL__USER}
      MYSQL_PASSWORD: ${MYSQL__PASSWORD}
      MYSQL_DATABASE: db_educambi
    ports:
      - "3306:3306"
    networks:
      - educambi
    volumes:
      - data:/var/lib/mysql
      - ./config/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-app-container

networks:
  educambi:
    driver: bridge

volumes:
  data: